export const reducerCases = {
    SET_TOKEN: "SET_TOKEN",
    SET_COVER_ID:"SET_COVER_ID",
    SET_ACCENT:"SET_ACCENT",
    SET_FOR_YOU:"SET_FOR_YOU",
    SET_TOP_TRACKS:"SET_TOP_TRACKS",
    SET_USER: "SET_USER",
    SET_PLAYLISTS: "SET_PLAYLISTS",
    SET_PLAYING: "SET_PLAYING",
    SET_PLAYER_STATE: "SET_PLAYER_STATE",
    SET_SONG_URL:"SET_SONG_URL"
    
  };